### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by harshthakur92** [Mirch/OzNet#3]
ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.NoWriteNoSeekStreamContent'.

![errorpng](https://user-images.githubusercontent.com/19525609/44996737-35c11880-afc7-11e8-8973-172e63887168.png)

@Mirch  @zodchiy

**Comment by zodchiy** [comment]
Can you show more code?

**Comment by harshthakur92** [comment]
I am calling this method.
![event](https://user-images.githubusercontent.com/19525609/44996912-3a3a0100-afc8-11e8-909e-da0068edcb42.png)

and my routes.json is 

![json](https://user-images.githubusercontent.com/19525609/44996919-4b830d80-afc8-11e8-89c2-1230788d25a4.png)

@zodchiy @Mirch

**Comment by denysetiawan28** [comment]
I have same problem like you but somehow i fix the problem with this.
![image](https://user-images.githubusercontent.com/10387234/45046301-f31f3f00-b09f-11e8-8589-e7c07e4d9b42.png)
Result 
![image](https://user-images.githubusercontent.com/10387234/45046351-177b1b80-b0a0-11e8-91da-4ae1cd92c9f7.png)
I think the using section is disposing the response, so when that response called on startup, .NET will throw an error.

**Comment by harshthakur92** [comment]
@denysetiawan28  Thanks...
Now its working. :+1:

**Comment by Mirch** [comment]
@denysetiawan28  if you  could make a pull request with your solution, that would be great
